[env:node32s]
platform = espressif32
board = node32s
framework = arduino

; Serial Monitor settings
monitor_speed = 115200

; Build settings
build_flags = 
    -D CORE_DEBUG_LEVEL=5

; Library dependencies
lib_deps = 
    ; Add your libraries here 